EventBrightApplication/Models/Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EventBrightApplication.Models
{
    public class Event : IValidatableObject
    {
        [Key]
        public virtual int EventId { get; set; }
      
        [Display(Name = "Event Type")]
        public virtual EventType TypeId { get; set; }        
        public virtual EventType TypeName { get; set; }

        [Required]
        [StringLength(50)]
        public virtual string Title { get; set; }

        [StringLength(150)]
        public virtual string Description { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [Display(Name = "Start Date")]
        [greaterThanNow(ErrorMessage = "Date must be greater or equal to today's date.")]
        public virtual DateTime StartDate { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:hh:mm tt}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Time)]
        [Display(Name = "Start Time")]
        public virtual DateTime StartTime { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [Display(Name = "End Date")]
        public virtual DateTime EndDate { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:hh:mm tt}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Time)]
        [Display(Name = "End Time")]
        public virtual DateTime EndTime { get; set; }

        [Required]
        public virtual string Location { get; set; }        

        [Required]
        [Display(Name = "Organizer Name")]
        public virtual string OrganizerName { get; set; }

        [Display(Name = "Organizer Information")]
        public virtual string OrganizerInfo { get; set; }

        [Required]
        [Display(Name = "Maximum Tickets")]
        [notZero(0)]
        public virtual int MaxTickets { get; set; }
        [Required]
        [Display(Name = "Available Tickets")]
        [notZero(0)]
        public virtual int AvailableTickets { get; set; }

        [Required]
        public virtual string City { get; set; }

        [Required]
        public virtual string State { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            
            if (EndDate < StartDate)
            {
                yield return (new ValidationResult("End Date must be greater then the Start Date.", new[] { "EndDate" }));
            }            
        }
    }

}

EventBrightApplication/Models/EventType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EventBrightApplication.Models
{
    public class EventType
    {
        [Key]
        [Display(Name = "Type Id")]
        public virtual int TypeId { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Event Type")]
        public virtual string TypeName { get; set; }

        [StringLength(150)]
        [Display(Name = "Event Description")]
        public virtual string TypeDescription { get; set; }
    }
}

EventBrightApplication/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventBrightApplication.Models;

namespace EventBrightApplication.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        private EventBrightApplicationDB db = new EventBrightApplicationDB();

        [AllowAnonymous]
        // GET: Event
        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        [AllowAnonymous]
        // GET: Event/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Event/Create
        public ActionResult Create()
        {
            ViewBag.EventType= new SelectList(db.EventTypes, "TypeId", "TypeName");

            return View();
        }

        // POST: Event/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "EventId,TypeName,Title,Description,StartDate,StartTime,EndDate,EndTime,Location,OrganizerName,OrganizerInfo,MaxTickets,AvailableTickets,City,State")] Event @event)
        public ActionResult Create(Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        // GET: Event/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }

            ViewBag.EventType = new SelectList(db.EventTypes, "TypeId", "TypeName", @event.TypeId);
            return View(@event);
        }

        // POST: Event/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventId,Title,Description,StartDate,StartTime,EndDate,EndTime,Location,OrganizerName,OrganizerInfo,MaxTickets,AvailableTickets,City,State")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Event/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [AllowAnonymous]
        public ActionResult Search()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Find(string type, string location)
        {
            var events = GetEvents(type, location);
            if (events == null)
            {
                return PartialView("_NoResult", events);
            }
            return PartialView("_Find", events);
        }

        [AllowAnonymous]
        private List<Event> GetEvents(string searchtype, string searchlocation)
        { 
            return db.Events
                .Where(e => e.Title.Contains(searchtype)
                        || e.TypeName.TypeName.Contains(searchtype)
                        || searchtype == null
                        || searchtype == "Event or Event Type"
                        && e.City.Contains(searchlocation)
                        || e.Location.Contains(searchlocation)
                        || e.State.Contains(searchlocation)
                        || searchlocation == null
                        || searchlocation == "Location, City, or State")
                        .OrderBy(e => e.StartDate)
                        .ToList();
        }        
    }
}

EventBrightApplication/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EventBrightApplication.Models;

namespace EventBrightApplication.Controllers
{
    public class OrdersController : Controller
    {
        // GET: Orders
        public ActionResult Index()
        {
            Tickets order = Tickets.GetOrder(this.HttpContext);

            OrderViewModel vm = new OrderViewModel()
            {
                OrderItems = order.GetOrderItems(),
                TicketTotal = order.GetOrderTotal()
            };

            return View(vm);
        }

        //GET: Orders/AddToOrder
        public ActionResult AddToOrder(int id)
        {
            Tickets order = Tickets.GetOrder(this.HttpContext);
            order.AddToOrder(id);
            return RedirectToAction("Index");
            
        }
        
        //POST: Orders/RemoveFromOrder
        [HttpPost]
        public ActionResult RemoveFromOrder()
        {
            throw new NotImplementedException();
        }
    }
}

EventBrightApplication/Views/Event/Create.cshtml
@model EventBrightApplication.Models.Event

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Event</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TypeId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10 form-inline">
            @Html.DropDownList("EventType", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })  
            <button>@Html.ActionLink("Create a new event type", "Create", "EventType")</button>
        </div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrganizerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrganizerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrganizerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrganizerInfo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OrganizerInfo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OrganizerInfo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaxTickets, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaxTickets, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaxTickets, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AvailableTickets, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AvailableTickets, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AvailableTickets, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventBrightApplication/Views/Event/Delete.cshtml
@model EventBrightApplication.Models.Event

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizerInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizerInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxTickets)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableTickets)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EventBrightApplication/Views/Event/Details.cshtml
@model EventBrightApplication.Models.Event

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizerInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizerInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxTickets)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableTickets)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

    </dl>
</div>
<p>
    <button>@Html.ActionLink("Register", "AddToOrder", "Orders", new { id = Model.EventId }, null )</button>
    &nbsp;
    <button>@Html.ActionLink("Return Home", "Index", "Home")</button>
</p>

EventBrightApplication/Views/Event/Index.cshtml
@model IEnumerable<EventBrightApplication.Models.Event>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>        
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrganizerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrganizerInfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxTickets)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AvailableTickets)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrganizerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrganizerInfo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaxTickets)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AvailableTickets)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EventId }) |
            @Html.ActionLink("Details", "Details", new { id=item.EventId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EventId })
        </td>
    </tr>
}

</table>

EventBrightApplication/Views/Event/Search.cshtml
@{
    ViewBag.Title = "Search";
}
<center>
    <img src="~/Content/Images/compass-1342.png" width="350" />
    <br />
    <h1>Find an event near you!</h1>
    <br /><br />
    <div class="find">

        <div class="find_body" style="padding:0px 20px 30px 20px;">
            @using (Ajax.BeginForm("Find", "Event", new AjaxOptions
            {
                InsertionMode = InsertionMode.Replace,
                HttpMethod = "GET",
                OnFailure = "searchFailed",
                UpdateTargetId = "searchresults"
            }))
            {
                <input type="text" name="type" value="Event or Event Type" />
                <input type="text" name="location" value="Location, City, State" />
                <input type="submit" value="Search" />
            }
            <div id="searchresults"></div>
        </div>
    </div>
</center>

@section Scripts{
    <script src="~/Scripts/Apps/home_index.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

EventBrightApplication/Views/Event/_Find.cshtml
@model IEnumerable<EventBrightApplication.Models.Event>

<div id="searchresults" style="margin-top:10px;">
    <table>
        <tr style="background-color:cornflowerblue">
            <th style="width:200px; text-align:center;padding-bottom:3px;padding-left:5px;">
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th style="width:100px; text-align:center;padding-bottom:3px;">
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th style="width:100px; text-align:center;padding-bottom:3px;">
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th style="width:100px; text-align:center;padding-bottom:3px;">
                @Html.DisplayNameFor(model => model.State)
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr style=" border:1px solid cornflowerblue;">
                <td style="padding-left:3px;"> @Html.ActionLink(item.Title, "Details", "Event", new { id = item.EventId }, null)</td>
                <td style="text-align:center;">@item.StartDate</td>
                <td style="text-align:center;">@item.City</td>
                <td style="text-align:center;">@item.State</td>
            </tr>

        }
    </table>
</div>

EventBrightApplication/Views/Event/_NoResult.cshtml
@model IEnumerable<EventBrightApplication.Models.Event>

<div id="searchresults" style="margin-top:10px;">
    <table>
        <tr style="background-color:cornflowerblue">
            <th colspan="4" style="text-align:center;padding-bottom:3px;padding-left:5px;">
                No Event Found
            </th>
           
        </tr>
        @foreach (var item in Model)
        {
            <tr style=" border:1px solid cornflowerblue;">
                <td style="padding-left:3px;"> @Html.ActionLink(item.Title, "Details", "Event", new { id = item.EventId }, null)</td>
                <td style="text-align:center;">@item.StartDate</td>
                <td style="text-align:center;">@item.City</td>
                <td style="text-align:center;">@item.State</td>
            </tr>

        }
    </table>
</div>